  globs := #[
    .one `Family.Brothers1419,
    .one `Family.TwinPrimes,
    .one `Family.DirichletJitterTime,
    .one `Closure.ArakelovFoundations,
    .one `Eutheos.Object,
    .one `Eutheos.Theta,
    .one `Eutheos.RationalTheta,
    .one `Eutheos.RamanujanFactorization,
    .one `Eutheos.EulerProductLemmas,
    .one `Eutheos.Bridge,
    .one `Eutheos.RH,
    .one `Lindelof.LindelofBridge,
    .one `Lindelof.GrowthBoundReal,
    .one `Siegel.SiegelZeroFree,
    .one `Siegel.SiegelZeroFreeElementary,
    .one `Siegel.SiegelZeroFreeRe1,
    .one `SelfSymmetry.Core,
    .one `SelfSymmetry.Desert,
    .one `SelfSymmetry.JitterSymmetry,
    .one `SelfSymmetry.TwinWormhole,
    .one `SelfSymmetry.ClayWitness,
    .one `Protocol.Chain,
    .one `ContradictionRoute.LanglandsWeilTransfer,
    .one `ContradictionRoute.GrowthRepulsionBridge
  ]
