-- Investigation 18: The WF recursion unfolds too eagerly. Use @[simp] or equation lemmas.
-- The core issue: `unfold myDiv` unfolds all the way because it's WF recursive.
-- We need to use the autogenerated equation lemmas.

theorem my_add_sub_cancel_right (n p : Nat) : n + p - p = n := by
  induction p with
  | zero => rw [Nat.add_zero, Nat.sub_zero]
  | succ m ih => rw [Nat.add_succ, Nat.succ_sub_succ_eq_sub]; exact ih

theorem my_mul_sub (p n : Nat) : p * (n + 1) - p = p * n := by
  rw [Nat.mul_add, Nat.mul_one, my_add_sub_cancel_right]

theorem not_mul_succ_lt_self (p k : Nat) (hp : 0 < p) : ¬ (p * (k + 1) < p) := by
  intro h
  have h1 : p * 1 ≤ p * (k + 1) := Nat.mul_le_mul_left p (Nat.succ_le_succ (Nat.zero_le k))
  rw [Nat.mul_one] at h1
  exact Nat.lt_irrefl p (Nat.lt_of_le_of_lt h1 h)

-- Use structural recursion via a helper that avoids WF issues:
-- Instead of WF, use a fuel-based approach with Nat.rec
def myDivFuel : Nat → Nat → Nat → Nat
  | 0, _, _ => 0                    -- fuel exhausted
  | _ + 1, 0, _ => 0               -- p = 0
  | _ + 1, _, 0 => 0               -- N = 0 (base)
  | fuel + 1, p, N =>
    if N < p then 0
    else myDivFuel fuel p (N - p) + 1

-- For p * k / p, we need at most k steps, so fuel = k works.
-- But the fuel-based approach has the issue that we need to pick the right fuel.
-- Let's use N as fuel:

def myDiv (N p : Nat) : Nat :=
  if p = 0 ∨ N < p then 0
  else myDiv (N - p) p + 1
termination_by N
decreasing_by
  rename_i h
  have hp : p ≠ 0 := fun e => h (Or.inl e)
  have hge : p ≤ N := Nat.le_of_not_lt (fun e => h (Or.inr e))
  exact Nat.sub_lt (Nat.lt_of_lt_of_le (Nat.pos_of_ne_zero hp) hge) (Nat.pos_of_ne_zero hp)

-- Check the auto-generated equation lemma:
#check @myDiv.eq_1  -- This might work

-- Alternative: use simp [myDiv]
theorem myDiv_lt (N p : Nat) (h : p = 0 ∨ N < p) : myDiv N p = 0 := by
  simp [myDiv, h]

theorem myDiv_ge (N p : Nat) (h : ¬ (p = 0 ∨ N < p)) : myDiv N p = myDiv (N - p) p + 1 := by
  simp [myDiv, h]

#print axioms myDiv_lt
#print axioms myDiv_ge
